[package]
name = "shellpass"
version = "0.1.0"
edition = "2024"

[lib]
# cdylib is required for Android, lib is required for desktop
crate-type = ["cdylib", "lib"]

[dependencies]
anyhow = "1.0.102"
egui = "0.34.1"
egui_extras = { version = "0.34.1", features = ["default", "image"] }
env_logger = "0.11.10"
log = "0.4.29"
walkdir = "2.5.0"
winit = { version = "0.30.13", default-features = false }

[target.'cfg(target_os = "linux")'.dependencies]
eframe = { version = "0.34.1", default-features = false, features = ["accesskit", "wgpu"] }

[target.'cfg(target_os = "android")'.dependencies]
eframe = { version = "0.34.1", default-features = false, features = ["wgpu", "android-native-activity"] }
android_logger = "0.15.1"

[package.metadata.android]
build_targets = ["armv7-linux-androideabi", "aarch64-linux-android"]

[package.metadata.android.sdk]
min_sdk_version = 23
target_sdk_version = 35
